<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language [
<!ELEMENT language (info+ , text+)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ATTLIST info id ID #IMPLIED>
<!ATTLIST text id ID #IMPLIED>
]>
<language>
    <info id="name">Italiano</info>
    <info id="alias">it</info>
    <!-- ======================== A ======================== -->
    <text id="ttAccountActivation">Attivazione account</text>
    <text id="ttActive">Attivo</text>
    <text id="ttActivate">Attiva</text>
    <text id="ttAdd">Aggiungi</text>
    <text id="ttAddSelectedStudents">Aggiungi studenti selezionati</text>
    <text id="ttAdministration">Amministrazione</text>
    <text id="ttAdministrator">Amministratore</text>
    <text id="ttAdminWelcome">Benvenuto nel pannello d'amministrazione\nIl sistema include:</text>
    <text id="ttAlias">Codice ISO 639-1</text>
    <text id="ttAndExit">ed Esci</text>
    <text id="ttAnswer">Risposta</text>
    <text id="ttAnswers">Risposte</text>
    <text id="ttArchive">Archivia</text>
    <text id="ttArchived">Archiviato</text>
    <text id="ttAssignSubject">Assegna Materia</text>
    <text id="ttAutomatic">Automatico</text>
    <!-- ======================== B ======================== -->
    <text id="ttBlocked">Bloccato</text>
    <text id="ttBlock">Blocca</text>
    <text id="ttUnblock">Sblocca</text>
    <text id="ttBonus">Bonus</text>
    <!-- ======================== C ======================== -->
    <text id="ttCancel">Annulla</text>
    <text id="ttChangeLanguage">Cambia lingua</text>
    <text id="ttChangeVersion">Cambia versione</text>
    <text id="ttCheck">Verifica...</text>
    <text id="ttClose">Chiudi</text>
    <text id="ttClosed">Chiuso</text>
    <text id="ttCorrect">Correggi</text>
    <text id="ttConfirm">Conferma</text>
    <text id="ttConfirmEmail">Conferma E-mail</text>
    <text id="ttConfirmPassword">Conferma Password</text>
    <text id="ttCreate">Crea</text>
    <!-- ==================== CONFIRMS ===================== -->
    <text id="ttCArchiveExam">Sei sicuro di voler archiviare l'esame?\nNon sarà possibile consegnare ulteriori test e tutte le domande da correggere dei test consegnati totalizzeranno 0 punti.\nL'operazione non potrà essere annullata! Continuare?</text>
    <text id="ttCBlockTest">Sei sicuro di voler bloccare questo test?</text>
    <text id="ttCChangeStatus">Sei sicuro di voler impostare lo stato della domanda a _STATUS_?</text>
    <text id="ttCConfirmTest">Vuoi confermare il punteggio finale?\nQuesto test verrà archiviato! Continuare?</text>
    <text id="ttCDeleteAnswer">Sei sicuro di voler eliminare questa risposta e le sue traduzioni?\nL'operazione non potrà essere annullata! Continuare?</text>
    <text id="ttCDeleteExam">Sei sicuro di voler eliminare questo esame?\nTutti i test in corso, consegnati e archiviati verranno eliminati.\nL'operazione non potrà essere annullata! Continuare?</text>
    <text id="ttCDeleteQuestion">Sei sicuro di voler eliminare questa domanda e le sue traduzioni?\nL'operazione non potrà essere annullata! Continuare?</text>
    <text id="ttCDeleteRoom">Sei sicuro di voler eliminare questa stanza?\nL'operazione non potrà essere annullata!\nContinuare?</text>
    <text id="ttCDeleteSubject">Sei sicuro di voler eliminare questa materia?\nI seguenti elementi verranno PERMANENTEMENTE eliminati:\n - Materia\n - Tutti gli argomenti\n - Tutte le domande e le risposte con le relative traduzioni\n - Tutte le impostazioni d'esame\n - Tutti gli esami e i test attivi e archiviati\nL'operazione non potrà essere annullata! Continuare?</text>
    <text id="ttCDeleteSettings">Sei sicuro di voler eliminare queste impostazioni d'esame?\nL'operazione non potrà essere annullata! Continuare?</text>
    <text id="ttCDeleteTopic">Sei sicuro di voler eliminare questo argomento?\nI seguenti elementi verranno PERMANENTEMENTE eliminati:\n - Argomento\n - Tutte le domande con le relative traduzioni\n - Tutte le risposte con le relative traduzioni\nL'operazione non potrà essere annullata! Continuare?</text>
    <text id="ttCDiscardEdits">Le modifiche verranno perse.\nUscire?</text>
    <text id="ttCDiscardNew">L'elemento creato verrà perso.\nUscire?</text>
    <text id="ttCRegister">Sei sicuro di volerti registrare a questo esame?</text>
    <text id="ttCRegisterStudents">Sei sicuro di voler registrare gli studenti selezionati all'esame?</text>
    <text id="ttCRenewPassword">La password per l'esame verrà aggiornata.\nL'operazione non potrà essere annullata! Continuare?</text>
    <text id="ttCStartExam">Vuoi far partire questo esame?</text>
    <text id="ttCStartTest">Vuoi iniziare l'esame ora?\nTi verrà richiesta la password d'accesso all'esame.</text>
    <text id="ttCStopExam">Vuoi fermare questo esame?</text>
    <text id="ttCSubmitTest">Vuoi consegnare il test?\nL'operazione non potrà essere annullata! Continuare?</text>
    <text id="ttCTest">La password è corretta. Il tuo test è pronto e inizierà dopo il tuo click!</text>
    <text id="ttCUnblockTest">Sei sicuro di voler sbloccare questo test?</text>
    <text id="ttCUpdateLanguage">Sei sicuro di voler aggiornare i file di lingua?\nL'operazione non potrà essere annullata. Continuare?</text>
    <!-- ======================== D ======================== -->
    <text id="ttD1">Facile</text>
    <text id="ttD2">Intermedio</text>
    <text id="ttD3">Difficile</text>
    <text id="ttDistributionP">Proporzionale</text>
    <text id="ttDistributionU">Universale</text>
    <text id="ttDay">Giorno</text>
    <text id="ttDelete">Elimina</text>
    <text id="ttDescription">Descrizione</text>
    <text id="ttDifficulty">Difficoltà</text>
    <text id="ttDifficultyQuestions">Domande per difficoltà</text>
    <text id="ttDistribution">Distribuzione</text>
    <text id="ttDo">Esegui esame</text>
    <text id="ttDTAnswerInfo">Visualizzate _TOTAL_ risposte</text>
    <text id="ttDTAnswerFiltered">(filtrate da _MAX_ risposte totali)</text>
    <text id="ttDTAnswerEmpty">Nessuna risposta da visualizzare</text>
    <text id="ttDTExamInfo">Visualizzati _TOTAL_ esami in corso</text>
    <text id="ttDTExamFiltered">(filtrati da _MAX_ esami in corso totali)</text>
    <text id="ttDTExamEmpty">Nessun esame da visualizzare</text>
    <text id="ttDTQuestionInfo">Visualizzate _TOTAL_ domande</text>
    <text id="ttDTQuestionFiltered">(filtrate da _MAX_ domande totali)</text>
    <text id="ttDTQuestionEmpty">Nessuna domanda da visualizzare</text>
    <text id="ttDTRegisteredStudentInfo">Visualizzati _TOTAL_ studenti registrati</text>
    <text id="ttDTRegisteredStudentFiltered">(filtrati da _MAX_ studenti registrati totali)</text>
    <text id="ttDTRegisteredStudentEmpty">Nessuno studente registrato da visualizzare</text>
    <text id="ttDTStudentsInfo">Visualizzati _TOTAL_ studenti</text>
    <text id="ttDTStudentsFiltered">(filtrati da _MAX_ studenti totali)</text>
    <text id="ttDTStudentsEmpty">Nessuno studente da visualizzare</text>
    <text id="ttDTTeacherInfo">Visualizzati _TOTAL_ docenti</text>
    <text id="ttDTTeacherFiltered">(filtrati da _MAX_ docenti totali)</text>
    <text id="ttDTTeacherEmpty">Nessun docente da visualizzare</text>
    <text id="ttDTTestInfo">Visualizzati _TOTAL_ test</text>
    <text id="ttDTTestFiltered">(filtrati da _MAX_ test totali)</text>
    <text id="ttDTTestEmpty">Nessun test da visualizzare</text>
    <text id="ttDone">Esame completato</text>
    <text id="ttDuration">Durata</text>
    <!-- ======================== E ======================== -->
    <text id="ttEdit">Modifica</text>
    <text id="ttError">Errore</text>
    <text id="ttEmail">E-mail</text>
    <text id="ttEnd">Fine</text>
    <text id="ttEverywhere">Ovunque</text>
    <text id="ttExam">Esame</text>
    <text id="ttExams">Esami</text>
    <text id="ttExit">Uscita</text>
    <text id="ttExtra">Extra</text>
    <text id="ttExamsArchive">Archivia</text>
    <text id="ttExamsInProgress">Esami in corso</text>
    <!-- ===================== ERRORS ====================== -->
    <text id="ttEActivationFails">Attivazione fallita!</text>
    <text id="ttEAlreadyRegistered">Lo studente è già registrato a questo esame!</text>
    <text id="ttEAnswerInSet">L'operazione non può essere completata. La risposta è usata in alcuni test!</text>
    <text id="ttEAnswerNotFound">Risposta non trovata</text>
    <text id="ttEAnswers">Si è verificato un problema con le risposte.\nContattare il docente o l'amministratore.</text>
    <text id="ttEDatabase">Errore nel database!</text>
    <text id="ttEDates">Date non corrette!</text>
    <text id="ttEEditRoomAll">'All' non pùò essere modificata!</text>
    <text id="ttEEmailAlreadyRegistered">E-mail già registrata!</text>
    <text id="ttEEmailNotRegistered">E-mail non registrata!</text>
    <text id="ttEEmailNotValid">L'email inserita non è valida! Inserisci un'indirizzo email valido</text>
    <text id="ttEEmailsNotMatch">Le due email non corrispondono!</text>
    <text id="ttEEmptyFields">Uno o più campi sono vuoti!</text>
    <text id="ttEExamArchived">L'operazione non può essere completata. L'esame è stato già archiviato!</text>
    <text id="ttEExamNotFound">Esame non trovato!</text>
    <text id="ttEExamNotStarted">Non puoi iniziare il test. L'esame non è ancora stato avviato!</text>
    <text id="ttEExamStarted">L'operazione non può essere completata perché l'esame è già iniziato!</text>
    <text id="ttEExamWaiting">L'operazione non può essere completata perché l'esame non è mai stato avviato!</text>
    <text id="ttEExamsNotArchivedDeleteTopic">L'operazione non può essere completata perché uno o più esami non ancora archiviati contengono domande contenute in questo argomento!</text>
    <text id="ttEExamsNotArchivedEditTestSettings">L'operazione non può essere completata perché queste impostazioni sono utilizzate da almeno un esame non ancora archiviato.\nSarà possibile aggiornare unicamente nome e descrizione. Continuare?</text>
    <text id="ttEExamsNotArchivedDeleteTestSettings">L'operazione non può essere completata perché queste impostazioni sono utilizzate da almeno un esame non ancora archiviato.</text>
    <text id="ttEIncorrectField">Uno o più campi non sono corretti!</text>
    <text id="ttELogin">E-mail e/o Password non sono corretti!</text>
    <text id="ttEMainLanguageEmpty">La lingua principale della materia non può essere vuota!</text>
    <text id="ttEMandatoryQuestion">Questa è una domanda obbligatoria delle impostazioni d'esame '_TESTSETTING_': non è possibile cancellara o modificarne difficoltà e argomento.</text>
    <text id="ttENotAuthorized">Il tuo client non è autorizzato.\nContatta il docente o l'amministratore.</text>
    <text id="ttENoStudentsToRegister">Nessun studente da registrare all'esame!</text>
    <text id="ttEOldPasswordWrong">La vecchia password non corrisponde!</text>
    <text id="ttEPassword">Password errata!</text>
    <text id="ttEPasswordShort">La password è troppo breve. Deve avere una lunghezza minima di 8 caratteri!</text>
    <text id="ttEPasswordsNotMatch">Le due password non corrispondono!</text>
    <text id="ttEQuestAnswPicker">Errore durante il recupero di domande e risposte.\nContattare il docente!</text>
    <text id="ttEQuestionInSet">L'operazione non può essere completata. La domanda è usata in alcuni test!</text>
    <text id="ttEQuestionNotFound">Domanda non trovata!</text>
    <text id="ttEQuestionType">Tipo di domanda non corretto!</text>
    <text id="ttERegFailedQuestions">Registrazione fallita: poche domande! Contattare il docente.</text>
    <text id="ttERoomAllDelete">'Tutte' non può essere eliminata!</text>
    <text id="ttERoomUsed">L'operazione non può essere completata. La stanza è usata in alcuni esami!</text>
    <text id="ttESaveBeforeNew">Prima di creare un nuovo elemento salva o cancella quello appena creato.</text>
    <text id="ttESelectQuestionType">Selezionare uno dei tipi di domanda disponibili!</text>
    <text id="ttESelectSubject">Selezionare uno dei propri corsi!</text>
    <text id="ttESelectTestSettings">Selezionare una delle impostazioni d'esame!</text>
    <text id="ttESetNotFound">Set di domande non trovato!</text>
    <text id="ttETestBlockedSubmitted">L'operazione non può essere completata. Questo test è stato bloccato o è stato già consegnato!</text>
    <text id="ttETestAlreadyArchived">L'operazione non può essere completata. Questo test è stato già corretto e archiviato!</text>
    <text id="ttETestAlreadySubmitted">L'operazione non può essere completata. Il test è stato già consegnato o archiviato!</text>
    <text id="ttETestNotArchived">L'operazione non può essere completata. Questo test non è stato archiviato!</text>
    <text id="ttETestNotFound">Test non trovato!</text>
    <text id="ttETestSettingDeleteQuestion">L'operazione non può essere completata perché la domanda è obbligatoria nelle seguenti impostazioni d'esame:</text>
    <text id="ttETestSettingDeleteTopic">L'operazione non può essere completata perché alcune domande di questo argomento sono utilizzate nelle seguenti impostazioni d'esame:</text>
    <text id="ttETestsNotArchived">Alcuni test non sono stati archiviati! Correggere prima tutti i test.</text>
    <text id="ttETimeExpired">Il tempo disponibile è finito!</text>
    <text id="ttETranslationExists">La traduzione nella lingua selezionata è già presente!</text>
    <text id="ttEUserNotFound">Utente non trovato!</text>
    <text id="ttEValues">Alcuni valori non sono corretti!</text>
    <!-- ======================== F ======================== -->
    <text id="ttFalse">Falso</text>
    <text id="ttFinalScore">Punteggio finale</text>
    <!-- ======================== G ======================== -->
    <text id="ttGeneralInformations">Informazioni Generali</text>
    <!-- ======================== H ======================== -->
    <text id="ttHours">ore</text>
    <!-- ======================= HELP ====================== -->
    <text id="ttHAnswPanel">Due click per modificare la risposta selezionata</text>
    <text id="ttHQuestLanguagesPanel">Un click per la traduzione\ndella domanda selezionata</text>
    <text id="ttHQuestPanel">Un click per selezionare la domanda e vederne l'anteprima, due click per modificare domanda e risposte. Doppio click sulle bandierine per attivare e disattivare le domande nei test</text>
    <text id="ttHQuestPreviewPanel">Le risposte con sfondo arancione non sono tradotte nella lingua richiesta</text>
    <text id="ttHQuestTopicPanel">Un click per filtrare le domande,\ndoppio per modificare l'argomento</text>
    <!-- ======================== I ======================== -->
    <text id="ttInfo">Informazioni</text>
    <text id="ttIPEnd">IPv4 Fine</text>
    <text id="ttIPStart">IPv4 Inizio</text>
    <text id="ttInactive">Inattivo</text>
    <!-- ======================== J ======================== -->
    <text id="ttJoin">Iscriviti</text>
    <!-- ======================== K ======================== -->
    <!-- ======================== L ======================== -->
    <text id="ttLanguage">Lingua</text>
    <text id="ttLanguages">Lingue</text>
    <text id="ttLogin">Entra</text>
    <text id="ttLoginOk">Login completato!</text>
    <text id="ttLogout">ESCI</text>
    <!-- ======================== M ======================== -->
    <text id="ttMailLostPassword">Per impostare una nuova password clicca il link seguente:\n\n_LINK_\n\nSe non hai richiesto il reset della password allora ignora questa email.</text>
    <text id="ttMailCredentials">Ciao _USERNAME_,\nDi seguito sono riportate le tue credenziali di accesso:\n\nE-mail : _USEREMAIL_ \n Password : _USERPASSWORD_</text>
    <text id="ttMailNewTeacher">Benvenuto in _SYSTEMNAME_.\n\nPer attivare il tuo account clicca il link seguente e imposta la tua password personale:</text>
    <text id="ttMainLanguage">Lingua principale</text>
    <text id="ttManage">Gestisci</text>
    <text id="ttMandatory">Fisse</text>
    <text id="ttManual">Manuale</text>
    <text id="ttMinutes">minuti</text>
    <text id="ttMyExams">I miei esami</text>
    <text id="ttMySettings">Le mie impostazioni</text>
    <text id="ttMySubjects">Seleziona un corso</text>
    <!-- ==================== MESSAGES ===================== -->
    <text id="ttMActivation">Password impostata correttamente.\nVerrai portato alla tua Homepage</text>
    <text id="ttMAnswerDeleted">Risposta eliminata con successo</text>
    <text id="ttMConfirm">Test confermato e archiviato correttamente</text>
    <text id="ttMUserCreated">Creazione completata: ti è stata inviata una e-mail per completare la registrazione.\nControlla anche nella cartella Spam</text>
    <text id="ttMEdit">Modifiche salvate correttamente</text>
    <text id="ttMExamArchived">Esame archiviato con successo</text>
    <text id="ttMExamDeleted">Esame eliminato con successo</text>
    <text id="ttMExamStarted">Esame avviato con successo</text>
    <text id="ttMExamStopped">Esame fermato con successo</text>
    <text id="ttMLanguageCreated">Traduzione creata con successo</text>
    <text id="ttMLanguageSaved">Traduzione salvata con successo</text>
    <text id="ttMLanguageUpdated">Traduzione aggiornata con successo</text>
    <text id="ttMNewRoom">Stanza creata con successo</text>
    <text id="ttMNewSettings">Impostazioni d'esame create con successo</text>
    <text id="ttMNewSubject">Materia creata con successo</text>
    <text id="ttMNewTopic">Argomento creato con successo</text>
    <text id="ttMPasswordRenewed">Password d'esame rinnovata con successo</text>
    <text id="ttMQuestionDeleted">Domanda eliminata con successo</text>
    <text id="ttMRegistration">Sei stato correttamente registrato all'esame</text>
    <text id="ttMResetConfirmed">Richiesta completata: ti è stata inviata una e-mail per reimpostare la tua password. Controlla anche nella cartella Spam</text>
    <text id="ttMRoomDeleted">Stanza eliminata con successo</text>
    <text id="ttMSelectLanguage">Seleziona la lingua da gestire</text>
    <text id="ttMSettingsDeleted">Impostazioni d'esame eliminate con successso</text>
    <text id="ttMStudentsRegistered">Studenti registrati con successo all'esame</text>
    <text id="ttMSubjectDeleted">Materia eliminata con successo</text>
    <text id="ttMSubjectQuestions">Per gestire gli argomenti e le domande seleziona il corso</text>
    <text id="ttMSubjectSettings">Per gestire le impostazioni d'esame seleziona il corso</text>
    <text id="ttMTestBlocked">Test bloccato con successo</text>
    <text id="ttMTestSubmitted">Test consegnato con successo</text>
    <text id="ttMTestUnblocked">Test sbloccato con successo</text>
    <text id="ttMTopicDeleted">Argomento eliminato con successo</text>
    <!-- ======================== N ======================== -->
    <text id="ttName">Nome</text>
    <text id="ttNew">Nuovo</text>
    <text id="ttNext">Avanti</text>
    <text id="ttNewAnswer">Nuova risposta</text>
    <text id="ttNewCredentials">Nuove credenziali</text>
    <text id="ttNewLanguage">Nuova lingua</text>
    <text id="ttNewPassword">Nuova password</text>
    <text id="ttNewQuestion">Nuova domanda</text>
    <text id="ttNewRegistration">Nuova registrazione</text>
    <text id="ttNewRoom">Nuova stanza</text>
    <text id="ttNewTeacher">Nuovo docente</text>
    <text id="ttNewTestSettings">Nuove impostazioni</text>
    <text id="ttNewStudent">Nuovo studente</text>
    <text id="ttNewSubject">Nuova materia</text>
    <text id="ttNewTopic">Nuovo argomento</text>
    <text id="ttNewUser">Nuovo utente</text>
    <text id="ttNo">No</text>
    <text id="ttNoAnswers">Nessuna risposta disponibile per questa domanda</text>
    <text id="ttNoExams">Nessun esame disponibile per questa materia</text>
    <text id="ttNoExamInProgress">Nessun esame in corso</text>
    <text id="ttNoInfo">Non ci sono informazioni per questo esame</text>
    <text id="ttNoQuestions">Nessuna domanda disponibile per questo argomento</text>
    <text id="ttNoRooms">Nessuna stanza creata: 'Tutte' è l'unica disponibile</text>
    <text id="ttNoSettings">Nessuna impostazione disponile per questa materia</text>
    <text id="ttNoSubjects">Nessuna materia disponibile</text>
    <text id="ttNoTestToCorrect">Nessun test da correggere</text>
    <text id="ttNoUserRegistered">Nessuno studente registrato a questo esame</text>
    <!-- ======================== O ======================== -->
    <text id="ttOldPassword">Vecchia Password</text>
    <text id="ttEssayQuestion">Domanda a risposta aperta</text>
    <!-- ======================== P ======================== -->
    <text id="ttPassword">Password</text>
    <text id="ttPasswordLost">Password persa?</text>
    <text id="ttProfile">Profilo</text>
    <!-- ======================== Q ======================== -->
    <text id="ttQuestion">Domanda</text>
    <text id="ttQuestionPreview">Anteprima della domanda</text>
    <text id="ttQuestions">Domande</text>
    <text id="ttQEc">Calcolatrice</text>
    <text id="ttQEp">Tavola Periodica</text>
    <text id="ttQTMC">Risposta singola</text>
    <text id="ttQTMCDescription">In una domanda a risposta singola il partecipante sceglie una singola risposta tra tutte quelle fornite.</text>
    <text id="ttQTMR">Risposta multipla</text>
    <text id="ttQTMRDescription">Una domanda a risposta multipla è simile a quella a Risposta Singola, con la differenza che il partecipante può rispondere scegliendo una o più risposte tra quelle fornite.</text>
    <text id="ttQTES">Risposta aperta</text>
    <text id="ttQTESDescription">Una domanda a risposta aperta permette al partecipante di rispondere inserendo un testo libero senza limiti di caratteri. È possibile usare questo tipo di domanda per chiedere opinioni o suggerimenti riguardo una particolare materia.</text>
    <text id="ttQTYN">Si / No</text>
    <text id="ttQTYNDescription">Una domanda Sì/No è una domanda a risposta singola che chiede al partecipante di rispondere con un "Sì" o un "No".</text>
    <text id="ttQTTF">Vera / Falso</text>
    <text id="ttQTTFDescription">Una domanda Vero/Falso è una domanda a risposta singola che chiede al partecipante di rispondere con un "Vero" o un "Falso".</text>
    <!-- ======================== R ======================== -->
    <text id="ttRandom">Casuali</text>
    <text id="ttRefresh">Aggiorna</text>
    <text id="ttRegister">Registrati</text>
    <text id="ttRegistrations">Registrazione</text>
    <text id="ttRegEnd">Chiusura registrazione</text>
    <text id="ttRenewPassword">Rinnova Password</text>
    <text id="ttReset">Reimposta</text>
    <text id="ttResetPassword">Reimposta Password</text>
    <text id="ttRole">Ruolo</text>
    <text id="ttRooms">Stanze</text>
    <!-- ======================== S ======================== -->
    <text id="ttSave">Salva</text>
    <text id="ttSaveAnswerInfo">Salva Informazioni Risposta</text>
    <text id="ttSaveLanguageFiles">Salva file di lingua</text>
    <text id="ttSaveLanguageXML">Salva file XML di lingua</text>
    <text id="ttSaveQuestionInfo">Salva Informazioni Domanda</text>
    <text id="ttScore">Punteggio</text>
    <text id="ttScoreFinal">Punteggio finale</text>
    <text id="ttScoreTest">Punteggio del test</text>
    <text id="ttScoreType">Tipo di punteggio</text>
    <text id="ttScoreMin">Punteggio minimo</text>
    <text id="ttSelectSubject">Seleziona un corso</text>
    <text id="ttSelectSubjectBefore">Selezionare prima un corso</text>
    <text id="ttSet">Imposta</text>
    <text id="ttSetPassword">Imposta la tua password</text>
    <text id="ttShowHide">Mostra/Nascondi</text>
    <text id="ttSettings">Impostazioni</text>
    <text id="ttStart">Inizia</text>
    <text id="ttStarted">Iniziato</text>
    <text id="ttStop">Ferma</text>
    <text id="ttStopped">Fermato</text>
    <text id="ttStartTest">Inizia test</text>
    <text id="ttStatus">Stato</text>
    <text id="ttStats">Statistiche</text>
    <text id="ttStudent">Studente</text>
    <text id="ttStudents">Studenti</text>
    <text id="ttST10">Decimi</text>
    <text id="ttST30">Trentesimi</text>
    <text id="ttST100">Centesimi</text>
    <text id="ttSubject">Materia</text>
    <text id="ttSubjects">Materie</text>
    <text id="ttSubmit">Consegna</text>
    <text id="ttSurname">Cognome</text>
    <text id="ttSystem">Sistema</text>
    <!-- ======================== T ======================== -->
    <text id="ttTeacher">Docente</text>
    <text id="ttTeachers">Docenti</text>
    <text id="ttTest">Test</text>
    <text id="ttTests">Test</text>
    <text id="ttTestToCorrect">Tests da correggere</text>
    <text id="ttText">Testo</text>
    <text id="ttTime">Ora</text>
    <text id="ttTimeEnd">Ora di fine</text>
    <text id="ttTimeStart">Ora di inizio</text>
    <text id="ttTimeUsed">Tempo usato</text>
    <text id="ttTopic">Argomento</text>
    <text id="ttTopics">Argomenti</text>
    <text id="ttTopicsAndQuestions">Argomenti e Domande</text>
    <text id="ttTopicsQuestions">Domande per argomenti</text>
    <text id="ttTranslations">Traduzioni</text>
    <text id="ttTrue">Vero</text>
    <text id="ttType">Tipo</text>
    <!-- ======================== U ======================== -->
    <text id="ttUsers">Utenti</text>
    <!-- ======================== V ======================== -->
    <text id="ttView">Vedi</text>
    <!-- ======================== W ======================== -->
    <text id="ttWelcome">Benvenuto</text>
    <text id="ttWaiting">Attesa</text>
    <text id="ttWarning">Attenzione</text>
    <!-- ======================== X ======================== -->
    <!-- ======================== Y ======================== -->
    <text id="ttYes">Sì</text>
    <!-- ======================== Z ======================== -->
</language>
